<a href="https://colab.research.google.com/github/hanjadavi03-max/FOR-YOU-/blob/main/linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_excel("/content/spotify_music_dataset_1000.xlsx")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_name        1000 non-null   object
 1   artist            1000 non-null   object
 2   genre             1000 non-null   object
 3   popularity        1000 non-null   int64
 4   duration_ms       1000 non-null   int64
 5   danceability      1000 non-null   float64
 6   energy            1000 non-null   float64
 7   loudness          1000 non-null   float64
 8   speechiness       1000 non-null   float64
 9   acousticness      1000 non-null   float64
 10  instrumentalness  1000 non-null   float64
 11  liveness          1000 non-null   float64
 12  valence           1000 non-null   float64
 13  tempo             1000 non-null   float64
dtypes: float64(9), int64(2), object(3)
memory usage: 109.5+ KB

In [4]:
df.describe()

,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
count,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,55.2050,225167.619000,0.563672,0.558675,-6.990800,0.133601,0.443666,0.406490,0.259477,0.528017,125.402700
std,25.9385,43087.484347,0.214814,0.232332,2.906135,0.065591,0.258912,0.231103,0.137569,0.248078,31.289417
min,10.0000,150048.000000,0.200000,0.151000,-12.000000,0.020000,0.011000,0.001000,0.030000,0.100000,70.200000
25%,34.0000,186784.000000,0.374500,0.354750,-9.410000,0.077750,0.213000,0.210000,0.140000,0.301750,97.875000
50%,55.0000,226979.000000,0.555500,0.571000,-6.975000,0.133500,0.440000,0.409000,0.253000,0.524000,125.750000
75%,77.0000,262796.000000,0.748000,0.741250,-4.390000,0.189000,0.670000,0.601250,0.379000,0.741500,152.175000
max,100.0000,299549.000000,0.949000,0.979000,-2.010000,0.249000,0.900000,0.800000,0.500000,0.950000,180.000000

In [9]:
df.sample(10)

,track_name,artist,genre,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,New_olumn
361,Rock Track 362,Golden Hour,rock,20,192467,0.458,0.410,-5.47,0.183,0.549,0.316,0.447,0.764,173.3,False
415,Classical Track 416,Solar Avenue,classical,73,292475,0.806,0.655,-7.07,0.070,0.597,0.363,0.238,0.611,70.7,True
678,Country Track 679,Urban Lights,country,69,194054,0.872,0.943,-7.18,0.144,0.227,0.136,0.474,0.695,81.6,True
884,Rock Track 885,Aria Bloom,rock,19,169369,0.578,0.734,-4.67,0.025,0.671,0.433,0.462,0.181,134.7,False
511,Lo-Fi Track 512,Echo Park,lo-fi,18,175979,0.815,0.783,-6.71,0.185,0.868,0.137,0.384,0.104,149.8,False
408,Classical Track 409,Urban Lights,classical,41,262081,0.504,0.185,-4.65,0.107,0.288,0.489,0.379,0.605,127.8,True
250,Lo-Fi Track 251,Urban Lights,lo-fi,14,197731,0.652,0.914,-2.32,0.071,0.513,0.749,0.096,0.734,96.2,False
509,Rock Track 510,The Skylines,rock,14,284605,0.645,0.539,-2.91,0.030,0.278,0.008,0.075,0.205,136.2,False
240,Pop Track 241,Midnight Echo,pop,69,163274,0.326,0.626,-3.78,0.111,0.036,0.547,0.111,0.283,90.6,True
508,Hip-Hop Track 509,Luna Rivers,hip-hop,98,209395,0.431,0.324,-2.19,0.118,0.689,0.089,0.039,0.512,117.4,True

In [10]:
df.head()

,track_name,artist,genre,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,New_olumn
0,Rock Track 1,Ocean Drive,rock,13,222097,0.384,0.266,-10.98,0.190,0.495,0.472,0.045,0.180,95.6,False
1,Pop Track 2,Silver Coast,pop,81,202124,0.737,0.732,-7.80,0.123,0.258,0.695,0.387,0.236,116.5,True
2,Hip-Hop Track 3,Aria Bloom,hip-hop,37,238236,0.277,0.465,-8.41,0.099,0.245,0.035,0.246,0.206,171.5,True
3,Country Track 4,Midnight Echo,country,47,244800,0.633,0.735,-11.54,0.072,0.268,0.064,0.139,0.186,100.6,True
4,R&B Track 5,Ocean Drive,R&B,30,247040,0.466,0.706,-4.98,0.177,0.074,0.508,0.281,0.308,120.8,False

In [11]:
df.tail()

,track_name,artist,genre,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,New_olumn
995,Country Track 996,Maya Stone,country,56,291415,0.373,0.936,-6.69,0.106,0.099,0.133,0.328,0.625,162.8,True
996,Hip-Hop Track 997,Maya Stone,hip-hop,79,261153,0.844,0.381,-2.41,0.238,0.274,0.721,0.487,0.860,121.5,True
997,Indie Track 998,Luna Rivers,indie,10,169626,0.388,0.611,-8.88,0.232,0.556,0.767,0.058,0.449,85.8,False
998,Hip-Hop Track 999,Urban Lights,hip-hop,41,252560,0.790,0.686,-8.09,0.064,0.753,0.056,0.483,0.335,168.2,True
999,Lo-Fi Track 1000,Midnight Echo,lo-fi,96,189805,0.354,0.268,-9.25,0.095,0.577,0.416,0.276,0.756,135.8,True

In [12]:
df.drop_duplicates()

,track_name,artist,genre,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,New_olumn
0,Rock Track 1,Ocean Drive,rock,13,222097,0.384,0.266,-10.98,0.190,0.495,0.472,0.045,0.180,95.6,False
1,Pop Track 2,Silver Coast,pop,81,202124,0.737,0.732,-7.80,0.123,0.258,0.695,0.387,0.236,116.5,True
2,Hip-Hop Track 3,Aria Bloom,hip-hop,37,238236,0.277,0.465,-8.41,0.099,0.245,0.035,0.246,0.206,171.5,True
3,Country Track 4,Midnight Echo,country,47,244800,0.633,0.735,-11.54,0.072,0.268,0.064,0.139,0.186,100.6,True
4,R&B Track 5,Ocean Drive,R&B,30,247040,0.466,0.706,-4.98,0.177,0.074,0.508,0.281,0.308,120.8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Country Track 996,Maya Stone,country,56,291415,0.373,0.936,-6.69,0.106,0.099,0.133,0.328,0.625,162.8,True
996,Hip-Hop Track 997,Maya Stone,hip-hop,79,261153,0.844,0.381,-2.41,0.238,0.274,0.721,0.487,0.860,121.5,True
997,Indie Track 998,Luna Rivers,indie,10,169626,0.388,0.611,-8.88,0.232,0.556,0.767,0.058,0.449,85.8,False
998,Hip-Hop Track 999,Urban Lights,hip-hop,41,252560,0.790,0.686,-8.09,0.064,0.753,0.056,0.483,0.335,168.2,True
999,Lo-Fi Track 1000,Midnight Echo,lo-fi,96,189805,0.354,0.268,-9.25,0.095,0.577,0.416,0.276,0.756,135.8,True

In [13]:
df.dropna(subset='tempo')

,track_name,artist,genre,popularity,duration_ms,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,New_olumn
0,Rock Track 1,Ocean Drive,rock,13,222097,0.384,0.266,-10.98,0.190,0.495,0.472,0.045,0.180,95.6,False
1,Pop Track 2,Silver Coast,pop,81,202124,0.737,0.732,-7.80,0.123,0.258,0.695,0.387,0.236,116.5,True
2,Hip-Hop Track 3,Aria Bloom,hip-hop,37,238236,0.277,0.465,-8.41,0.099,0.245,0.035,0.246,0.206,171.5,True
3,Country Track 4,Midnight Echo,country,47,244800,0.633,0.735,-11.54,0.072,0.268,0.064,0.139,0.186,100.6,True
4,R&B Track 5,Ocean Drive,R&B,30,247040,0.466,0.706,-4.98,0.177,0.074,0.508,0.281,0.308,120.8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Country Track 996,Maya Stone,country,56,291415,0.373,0.936,-6.69,0.106,0.099,0.133,0.328,0.625,162.8,True
996,Hip-Hop Track 997,Maya Stone,hip-hop,79,261153,0.844,0.381,-2.41,0.238,0.274,0.721,0.487,0.860,121.5,True
997,Indie Track 998,Luna Rivers,indie,10,169626,0.388,0.611,-8.88,0.232,0.556,0.767,0.058,0.449,85.8,False
998,Hip-Hop Track 999,Urban Lights,hip-hop,41,252560,0.790,0.686,-8.09,0.064,0.753,0.056,0.483,0.335,168.2,True
999,Lo-Fi Track 1000,Midnight Echo,lo-fi,96,189805,0.354,0.268,-9.25,0.095,0.577,0.416,0.276,0.756,135.8,True

In [16]:
df.sort_values(['loudness'])

Empty DataFrame
Columns: [track_name, artist, genre, popularity, duration_ms, danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo, New_olumn]
Index: []

In [17]:
df.groupby('loudness').sum()['danceability']

Series([], Name: danceability, dtype: float64)

In [18]:
df.rename(columns={'valence' : 'danceability'})

Empty DataFrame
Columns: [track_name, artist, genre, popularity, duration_ms, danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, danceability, tempo, New_olumn]
Index: []

In [25]:
df.isnull().sum().sum()

np.int64(0)